#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

figlet "% Hamed Torky :) %"
python manage.py migrate
python manage.py collectstatic -c --noinput
python manage.py create_groups
python manage.py runserver_plus 0.0.0.0:8000
