version: '3'
services:
  web:
    container_name: "django_app"
    restart: always
    build: 
      context: .
      dockerfile: ./compose/production/DockerFile
    volumes:
      - .:/code/
      - web-static:/code/static
      - media:/code/media
    environment:
      DEBUG: 'true'

  nginx:
    restart: always
    image: nginx:1.21-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - web-static:/static

  redis:
    restart: always
    image: redis:6
    volumes:
      - redisdata:/data

  postgres:
    restart: always
    image: kartoza/postgis:13-3.1
    volumes:
      - pgdata:/var/lib/postgresql
      - dbbackups:/backups
    environment:
      - POSTGRES_DB={POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting


volumes:
  web-django:
  web-static:
  pgdata:
  redisdata:
  dbbackups:
  media: {}
  prometheus_data: { }

networks:
  monitoring:
    driver: bridge